use_frameworks!

platform :ios, '8.0'

target 'GSAModuleCategory_Example' do
  pod 'GSAModuleCategory', :path => '../'

  target 'GSAModuleCategory_Tests' do
    inherit! :search_paths

    
  end
pod 'CTMediator'
end
